version: '3.1'

services:

  db:
    container_name: ${DOCKER_MYSQL_CONTAINER_NAME}
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  
  wordpress:
    container_name: ${DOCKER_WP_CONTAINER_NAME}
    ports:
      - ${DOCKER_WP_CONTAINER_PORT}:80
    depends_on: 
      - db
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        wp_version: ${WORDPRESS_VERSION_TAG}
        php_version: ${PHP_VERSION}
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
      - ./logs/wp-debug.log:/var/www/html/wp-content/wp-debug.log
    environment:
      WORDPRESS_DB_HOST: db:${WORDPRESS_DB_PORT}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', ${WORDPRESS_DISPLAY_ERRORS} );
        define( 'WP_DEBUG_LOG', 'wp-content/wp-debug.log' );
        
  wpcli:
    container_name: ${DOCKER_WPCLI_CONTAINER_NAME}
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: db:${WORDPRESS_DB_PORT}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    depends_on:
      - db
      - wordpress

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: ${WORDPRESS_DB_PORT}
      UPLOAD_LIMIT: 50M
    restart: always
    ports:
      - ${DOCKER_PHPMYADMIN_CONTAINER_PORT}:80
    links:
      - db:db
    depends_on: 
      - db

volumes:
  wordpress:
  db: